name: CI

on:
  push:
    branches:
      - feature/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Run Ruby Tests
      run: |
        gem install bundler
        bundle install
        ruby lib/test/ruby/TestAll.rb

